#!/usr/bin/env node

const fs = require( 'fs' );
const path = require( 'path' );

const basePath = __dirname.replace( /\/scripts$/, '' )

addDefaultFiles( 'blacklist.txt', '' )
addDefaultFiles( '.env',
	[
		'PORT=8000',
		'TWITCHUSER=[YOUR-USERNAME-HERE]',
		'OAUTH=[YOUR-OAUTH-PASS HERE] # e.g. OAUTH=oauth:kjh12bn1hsj78445234',
		'YANDEX_KEY=[Yandex Key Here] # e.g. from https://translate.yandex.com/developers/keys',
	].join( '\n' ) + '\n'
)

function addDefaultFiles( name, defaultContent ) {
	const filePath = path.join( basePath, name )
	if( !fs.existsSync( filePath ) ) {
		fs.writeFileSync( filePath, defaultContent )
	}
}
